spring:
  application:
    name: botanic-ng
  redis:
    port: ${redisPort}
server:
  port: 9000

logging:
  level:
    org.springframework: INFO
    org.springframework.web: INFO
    com.hillert.botanic.config: INFO
